#{% set name = "irmsd" %}
#{% set version = "0.1.0" %}
#
#package:
#  name: {{ name|lower }}
#  version: {{ version }}
#
#source:
#  path: ../..
#
#build:
#  number: 0
#  script: "{{ PYTHON }} -m pip install . -vv"
#
#requirements:
#  host:
#    - python
#    - pip
#    - numpy
#    - scikit-build-core
#    - cmake
#    - ninja
#  run:
#    - python
#    - numpy
#
#test:
#  imports:
#    - irmsd
#  commands:
#    - python -c "import irmsd; print('ok')"
#
#about:
#  home: https://github.com/yourname/irmsd
#  license: BSD-3-Clause
#  summary: "irmsd: Python + Fortran acceleration"

